### PR TITLE
Add more methods to VenuesGateway

### PR DESCRIPTION
**Pull request by vojtasvoboda**
All implemented methods tested with my example application (https://github.com/vojtasvoboda/FoursquareDownloadExample). Comments taken from official Foursquare API documentation (https://developer.foursquare.com/docs/venues/venues).

### CODE REVIEW

**Comment by chriswoodford** [comment]
Hey, this is great, thanks a lot! Do you have an PHPUnit test coverage for this code? If not, would you be able to add some?

**Comment by vojtasvoboda** [comment]
Actually a tried to run tests by:

cd foursquare-php
composer install
cd tests
phpunit --bootstrap bootstrap.php .

And gets Undefined index: endpointUri

Can you write some quick example of running test and sample test in VenuesGatewayTest.php for one method to README.md? E.g. searchTest() or exploreTest()? I will write tests for rest methods.

You can now merge changes, because I tested them on my example app and it works. Other method doesn't have tests too, so it shouldn't be big problem for now.

**Comment by chriswoodford** [comment]
yes, for sure. let me make sure the test suite is working properly and i'll update the README with some more info and better documentation for the testing process. thanks for your input, i appreciate it!

**Comment by chriswoodford** [comment]
here's the info for running the test suite:
https://github.com/chriswoodford/foursquare-php/blob/master/CONTRIBUTING.md

let me know if that works for you, or if you still get some errors

**Comment by vojtasvoboda** [comment]
Great, I will try it and let you know or send you next pull request.

**Pull request merged**
